services:
  - type: web
    name: postiz
    env: docker
    plan: free
    autoDeploy: true
    ports:
      - port: 4200
        protocol: http
    startCommand: "pnpm run pm2"
    envVars:
      - key: APP_KEY
        value: base64:XdyE29arq5q0SPgRBZW2Eiiz99iedprKYEhVkxpGQh8=
